name: primeiro_passo
description: MVP adaptativo de empregabilidade e desenvolvimento profissional.
publish_to: 'none'
version: 0.5.5+10
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  shared_preferences: any
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  http: any
  provider: any
  url_launcher: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
flutter:
  uses-material-design: true



